---
strongswan_ca_cert_dn: "C=RU, O=YourCompany, CN=YourCompany Root CA"


### Tunnels ###
strongswan_tunnels:
  - id: "tunnel_1"
    start_action: "start"
    auth: "pubkey"
    #auth: "psk"
    #psk_secret: "1234"
    left:
      inventory_hostname: "gw2"
      public_ip: "5.4.3.1"
      local_ip: "10.10.2.12/24"
    right:
      inventory_hostname: "gw3"
      public_ip: "8.7.6.5"
      local_ip: "10.10.3.12/24"
