---
- name: set fact needs_certs
  set_fact:
    needs_certs: "{% set ns = namespace(needs_certs=false) %}{% for t in strongswan_tunnels %}{% if t.auth == 'pubkey' and (inventory_hostname == t.left.inventory_hostname or inventory_hostname == t.right.inventory_hostname) %}{% set ns.needs_certs = true %}{% endif %}{% endfor %}{{ ns.needs_certs }}"
  tags:
    - always

- name: build and install strongswan
  import_tasks: build.yml
  tags:
    - build
  notify:
    - restart strongswan

- name: generate certificates
  import_tasks: certs.yml
  tags:
    - certs
  when: needs_certs
  notify:
    - restart strongswan

- name: render config
  import_tasks: config.yml
  tags:
    - config
  notify:
    - restart strongswan

